import streamlit as st
import firebase_admin
from firebase_admin import db, credentials
import config

# Must be the first Streamlit command
st.set_page_config(page_title="OrbitIQ Ops", layout="wide", page_icon="🛰️")

# Initialize Firebase safely
if not firebase_admin._apps:
    try:
        cred = credentials.Certificate(config.SERVICE_ACCOUNT)
        firebase_admin.initialize_app(cred, {"databaseURL": config.DB_URL})
    except Exception as e:
        st.error(f"Firebase Init Error: {e}")

st.title("🛰️ Satellite Operations Command Center")
st.markdown("---")

# Enterprise KPI Ribbon
m1, m2, m3, m4, m5 = st.columns(5)
try:
    # Fetch real-time system metrics generated by the orchestrator
    metrics = db.reference("/SYSTEM_METRICS").get() or {}
    
    m1.metric("Connection", "ACTIVE", "124ms Latency")
    m2.metric("Power Output", "98.2W", "+1.2%")
    m3.metric("Temp (Internal)", "22°C", "Stable")
    m4.metric("Storage", "14%", "Nominal")
    m5.metric("System Status", metrics.get('status', 'IDLE'))
except Exception as e:
    st.error("Waiting for Telemetry Stream from Ground Station...")

st.info("👈 System operational. Select a module from the sidebar to view rest of the operations")